name: benchmark
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    env:
      BENCHER_API_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhcGlfa2V5IiwiZXhwIjo2MDYxMDQwOTY5LCJpYXQiOjE3NjYwNzM2NzQsImlzcyI6ImJlbmNoZXIuZGV2Iiwic3ViIjoibWF0dGlhcGl0b3NzaUBpY2xvdWQuY29tIiwib3JnIjpudWxsLCJzdGF0ZSI6bnVsbH0.w6R74gXj5GAeizCXXIZNyJ-ku6JMAlAKJAe0n3TjDTw
    strategy:
      matrix:
        bench:
          - ct_spawn
    steps:
      - uses: actions/checkout@v5

      - run: sudo apt-get update && sudo apt-get install -y valgrind

      - uses: taiki-e/install-action@cargo-binstall
      - name: Install gungraun-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
          )
          cargo binstall --no-confirm gungraun-runner --version $version

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark-${{ matrix.bench }}

      - uses: bencherdev/bencher@main
      - name: Run Bencher
        run: |
          bencher run --adapter rust_gungraun --err "cargo bench --bench ${{ matrix.bench }}"

      # - name: Run benchmarks
      #   run: cargo bench --bench ${{ matrix.bench }} -- --output-format=json | jq -s | tee output.json
      #
      # - name: Convert summary to benchmark format
      #   run: |
      #     jq '[.[] | {
      #     name: .id,
      #     unit: "instructions",
      #     value: .profiles[0].summaries.total.summary.Callgrind.Ir.metrics.Left.Int
      #     }]' output.json > benchmark-results.json
      #
      # - name: Store benchmark result
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     tool: "customSmallerIsBetter" # This is because github action doesn't support gungraun format with cargo tool
      #     output-file-path: benchmark-results.json
      #     # PrevioueyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhcGlfa2V5IiwiZXhwIjo2MDYxMDQwOTY5LCJpYXQiOjE3NjYwNzM2NzQsImlzcyI6ImJlbmNoZXIuZGV2Iiwic3ViIjoibWF0dGlhcGl0b3NzaUBpY2xvdWQuY29tIiwib3JnIjpudWxsLCJzdGF0ZSI6bnVsbH0.w6R74gXj5GAeizCXXIZNyJ-ku6JMAlAKJAe0n3TjDTws results
      #     external-data-json-path: ./cache/benchmark-results.json
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     # Alert if performance regresses by more than 10%
      #     alert-threshold: "110%"
      #     comment-on-alert: true
      #     fail-on-alert: false
